export const ActionTypes = {
    FETCH_DATA_REQUSET: "FETCH_DATA_REQUSET",
    FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
    FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",    
    SET_INPUT_MEDIA: "SET_INPUT_MEDIA",    
    SET_INPUT_TEXT: "SET_INPUT_TEXT",    
  };
