export const ActionTypes = {
    FETCH_DATA_REQUSET: "FETCH_DATA_REQUSET",
    FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
    FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",
    FETCH_ID_REQUSET: "FETCH_ID_REQUSET",
    FETCH_ID_SUCCESS: "FETCH_ID_SUCCESS",
    FETCH_ID_FAILURE: "FETCH_ID_FAILURE",      
    SET_INPUT_MEDIA: "SET_INPUT_MEDIA",    
    SET_INPUT_TEXT: "SET_INPUT_TEXT",    
    CLOSE_MODAL: "CLOSE_MODAL",    
    ADD_ITEM_TO_CARD: "ADD_ITEM_TO_CARD",    
    OPEN_CARD_MODAL: "OPEN_CARD_MODAL",    
  };
